### ISSUE TITLE
[RFC] Sparse Arrays & Associative Arrays

### ISSUE THREAD

**Issue by ghost** [universal-shell/wip#1]
### Sparse Arrays

bash has sparse arrays. That's to say you can assign to an array with an index out of bound:

``` bash
x=(1 2 3)
x[7]=8
x[5]=6
echo ${x[@]}  #=> 1 2 3 6 8
```

Sparse arrays can be implemented as an ordered map.
### Associative Arrays

bash also has associative arrays which are indexed with arbitary strings, but they are unordered maps.

``` bash
declare -A y=([1]=1 [2]=2 [11]=11)
echo ${y[@]}  #=> 11 1 2
```
### Ideas

We can unified sparse arrays and associative arrays into ordered maps, with all elements (or just values with numeric keys) numeric-sorted.

---

References:
- http://wiki.bash-hackers.org/syntax/arrays

**Comment by ghost** [comment]
Cons:
- Index N and -N may refer to the same element, which contrast to normal one-to-one mapping, so sparse arrays and associative arrays cannot be harmoniously join together if we want to provide negative indexing.
- Splicing sparse arrays could be hard.

**Comment by ghost** [comment]
Sparse Array + Ordered Map + Unordered Map = Maps X3

**Comment by jakwings** [comment]
Since null expansion is an error by default, sparse array would only cause chaos.
