### ISSUE TITLE
[RFC] Embed a tiny runtime system of another scripting language.

### ISSUE THREAD

**Issue by ghost** [universal-shell/wip#11]
This is not necessary, but seems helpful and interesting. The main purpose is to liberate the maintainers from writing ugly shell scripts with dirty hacks spread everywhere.

**Comment by ghost** [comment]
Some candidates are:
- JimTcl: http://jim.tcl.tk/
- Terra: http://terralang.org/
- Red: http://www.red-lang.org/
- Squirrel: http://squirrel-lang.org/
- Wren: https://munificent.github.io/wren/
- JerryScript: https://github.com/Samsung/jerryscript

Or concatenative languages?

**Comment by jakwings** [comment]
The embeded runtime should be able to clone any objects of the shell script?

**Comment by jakwings** [comment]
Bytecode for transpilers would be better?

**Comment by jakwings** [comment]
After trying the oh shell I think this is really a bad idea. (maintenance of complexity)
