### ISSUE TITLE
[RFC] Syntax: IO Redirection

### ISSUE THREAD

**Issue by ghost** [universal-shell/wip#18]
Bash style: `echo 2>&1` where 2 is a file descriptor for standard error output, not plain text "2".

How to avoid these with least special symbols?

**Comment by ghost** [comment]
How about …

``` rust
echo `2 > `1 | pipe

echo `$from > `$to | pipe
```

<code>&grave;</code> means the token followed is a file descriptor.

**Comment by jakwings** [comment]
The grave accent (or back-tick, back-quote) is used less frequently.

```rust
echo `$from > $to` | pipe
echo `$from > `$to | pipe
```
