### ISSUE TITLE
[RFC] A better "test" builtin function

### ISSUE THREAD

**Issue by ghost** [universal-shell/wip#2]
bash is confusing because it provides `test`, `[ ... ]` and `[[ ... ]]` for the same purpose: check file types and compare values.

There should only be one proper way to do that.

**Comment by ghost** [comment]
Also, this function is not required to behave the same as the bash one.

The `test` function can do three things:
1. Query file properties
2. Compare strings
3. Compare numbers

There could be three function instead, but what about the naming of new functions?

**Comment by jakwings** [comment]
With namespace support, this can be solved elegantly. (though without a terse syntax)
