### ISSUE TITLE
[RFC] Namespace & Alias

### ISSUE THREAD

**Issue by ghost** [universal-shell/wip#24]
Other than isolation of context, namespace is not that useful without a way to create short aliases.

**Comment by jakwings** [comment]
Should namespace be based on the file system?

**Comment by iology** [comment]
Rethinking…

**Comment by iology** [comment]
This is really useful to keep the builtin functionality unaffected by user-defined values.

**Comment by iology** [comment]
YES

**Comment by jakwings** [comment]
Let's reconsider the implementation of namespace.

**Comment by jakwings** [comment]
Namespace ≠ Module
Namespace ≠ Closure
Namespace ≠ Scope

**Comment by jakwings** [comment]
It is just a convenient machinery for isolation/organization/deletion of variables. One important task is how to distinguish namespaces from variable scopes.
