### ISSUE TITLE
[RFC] Delimiters for Word Splitting

### ISSUE THREAD

**Issue by ghost** [universal-shell/wip#27]
`<tab> <space> <newline>`?

`<nul>`?

Reinvent IFS? Phewwwwwwwwww…

**Comment by ghost** [comment]
This issue is specific to command substitution, e.g. in bash `$(echo $'\nA\nB\n')` expands into two words "A" and "b".

Conclusion: Remember, the shell is not a text editor.

**Comment by ghost** [comment]
Well, may have a new syntax to specify delimiters.

**Comment by ghost** [comment]
Or a new special command for variable assignment.

**Comment by jakwings** [comment]
Yes, it is

```bash
print "multi-line string" | read --delimiter "\r\n" -d "\n" -d "\r" xyz

read --delimiter "\r\n" -d "\n" -d "\r" --from "multi-line string" xyz
```
