### ISSUE TITLE
[RFC] Abstraction from terminals/OSes/POSIX

### ISSUE THREAD

**Issue by jakwings** [universal-shell/wip#29]
How to cut more connections to the operating systems?

* ASCII is the basic for text representation (and keywords for syntax).
* ~~UTF-8 determines valid bytes for plain text.~~
* Sure, there are directories and files.
* Use slashes `/` as path separators, `.` as "the current directory", `..` as "the parent directory", `/` at the start as "the root path of the local file system".
* There is only one user input at a time.
* ~~Use `#` as the comment starter?~~
* ~~Inherit PATH, HOME, PWD from the environment? Maybe TMPDIR too?~~
* ~~Export SHELL, SHLVL?~~
* Do you know `env 🇪🇺=Europe`?

**Comment by iology** [comment]
* Be extensible for OSs that support multiple URI schemes in the form `<scheme>:<path>`?
  May provides a scheme switcher.
