### ISSUE TITLE
[RFC] Theads

### ISSUE THREAD

**Issue by jakwings** [universal-shell/wip#39]
Thread->Fork (libuv), or Fork->Thread (boost.asio), this is a problem?

**Comment by iology** [comment]
Proposal: Every thread has a mailbox for `thread_send` and `thread_recv`. But then we may need a way to (de-)serialize the transferred data.

**Comment by iology** [comment]
It seems that I am providing a way for piping structured data. Hmm...

**Comment by iology** [comment]
Thread->Fork (libuv), or Fork->Thread (boost.asio), this is a problem?
