### ISSUE TITLE
[RFC] Documentation and Man page generator

### ISSUE THREAD

**Issue by jakwings** [universal-shell/wip#45]
Even though the fishy heads have poor memory, good documentation is still needed. We don't need thousands of indicators at the prompt to make the brain clunkier.

**Comment by iology** [comment]
Even though the fishy heads have poor memory, good documentation is still needed. We don't need thousands of indicators at the prompt to make the brain clunkier.

**Comment by jakwings** [comment]
May use Stonechat...
