### ISSUE TITLE
[RFC] Argument parsing

### ISSUE THREAD

**Issue by ghost** [universal-shell/wip#5]
1. Provide builtin functions like getopt(s)?
2. Enhance syntax of function definition?

**Comment by ghost** [comment]
This is also important to auto-completion.

**Comment by ghost** [comment]
Function definitions should not be too complicated. I'd prefer to separate argument parsing and function definitions.

The ideal design is that we can use the same syntax for argument parsing and auto completion, i.e.
- Auto Completion (for the user interface): provide full and detailed description about the function or any program
- Argument Parsing (for user-defined functions): specify the necessary attributes of switches and arguments with concise descriptions

**Comment by ghost** [comment]
Fun projects:
- https://github.com/mbrubeck/compleat
- https://github.com/docopt/docopt

**Comment by ghost** [comment]
For the whole command: `command parameter1 parameter2 parameter3 …`

`parameterN` is either a standalone argument, an option, an value for an option, or a name of a sub-command. So parameters may be formalized into this form:

`[global-options-and-arguments] [sub-commands-and-options-and-arguments]` e.g.

```
--global subcmd --switch subsubcmd --opt1 value1 --opt2 value2 -- arg1 arg2 arg3
```

How do we know the type of the parameter?

Rules to select:
1.  🌟 The main command and sub-commands can have any options and any arguments.
2.  🌟 Options of the same command can appear at any positions among the command parameters.
3.  🌟 A parameter that starts with a `-` and ends with an alphanumeric character is a short option.
4.  🌟 A parameter that starts with `--` followed by at least one alphanumeric character and only alphanumeric characters, is a long option.
5.  🌟 Any option may require no argument.
6.  🌟 Any option may require only one argument.
7.  🌟 Any option may require zero or one argument.
8.  🙅 Any option may require more than one arguments.
9.  🙅 Any option may require zero or more arguments.
10. 💭 Values of any option, if not optional, can be parameters right after the option, e.g.

    ```
    -o value1 value2 value3 ...
    --option value1 value2 value3 ...
    ```

11. 🌟 A option value, optional or not, can be joined to the option with one `=`, e.g.

    ```
    -o=value1
    --option=value1
    ```

    but optional value must be given this way, 👌 even if it is empty, e.g.

    ```
    --option=
    ```

12. 🙅 About rules 10 and 11, there exists such an equivalence relation for long options, respectively:

    ```
    -o value1 value2 value3 ...
    -o=value1 -o=value2 -o=value3 ...
    ```

    ```
    --option value1 value2 value3 ...
    --option=value1 --option=value2 --option=value3 ...
    ```

13. 🌟 Multiple short options, if none of them require any option value, can be grouped together into a special option started with a `-` and with all option names directly joined together, e.g.

    ```
    -a -b -c -v -v -v
    -abcvvv
    ```

14. 💭 The required value for an option can start with a `-`, e.g.

    ```
    -o - --option --
    ```

**Comment by iology** [comment]
Or use a hidden map to store special options.

**Comment by jakwings** [comment]
```
tree: function_name description
    tree: --flag_name description
        callbacks
    tree: command_name description
        tree: --flag_name description
            callbacks
        tree: ...
        callbacks
    tree: ...
    callbacks
```
