### ISSUE TITLE
[RFC] ASCII & Unicode & Locale

### ISSUE THREAD

**Issue by ghost** [universal-shell/wip#6]
Nowadays, Unicode (UTF-8, UTF-16, UTF-32, …) is the most widespread encoding standard which is also compatible with ASCII.

Among different encoding methods of Unicode characters, UTF-8 is most suitable for byte values manipulation and sorting.

---

References:
1. [UTF-8 Everywhere](http://utf8everywhere.org/)
2. [WTF-8](https://simonsapin.github.io/wtf-8/)
3. [xterm(1) now UTF-8 by default on OpenBSD](http://undeadly.org/cgi?action=article&sid=20160308204011)
4. [OpenBSD: Why and how you ought to keep multibyte character support simple](https://www.openbsd.org/papers/eurobsdcon2016-utf8.pdf)
5. [Parsing JSON is a Minefield](http://seriot.ch/parsing_json.php)

**Comment by ghost** [comment]
- Ignore all those `LANG*` and `LC_*` variables and use UTF-8 by default.
- No string collation for different countries/languages. Just take bytes.
- Let external programs solve those damn hard locale issues.
- Let the terminal (emulator) decide how to interpret invalid bytes.

**Comment by ghost** [comment]
However, this does not mean users cannot localize the user interface of the shell.

**Comment by ghost** [comment]
WTF-8 could be considered as the internal encoding if Windows is also a targeted platform.

**Comment by ghost** [comment]
💭 The [Safename](https://lwn.net/Articles/686789/) proposal sounds ridiculous.

We cannot do everything elegantly with a simple interface (`char** argv, char** envp`).

Follow-ups:

* https://lwn.net/SubscriberLink/784124/2595e4df117dc86a/
* https://lwn.net/SubscriberLink/784041/06801df80bc16e10/

What about unregistered code points? What about typos and mistakes in newer versions of the Unicode standard? And various newline characters and whitespace? Don't you want a stable filesystem?

**Comment by ghost** [comment]
To work around the character width problem about the broken `wcwidth` function in libc, we can use a custom width table:
-   Use an up-to-date width table (for Unicode 8.0), like http://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c (Unicode 5.0).
  
  Cons: The terminal the shell is running in may not use the same width table.
-   Adapt the width table for the terminal by using the [VT100 control sequence](https://www.vt100.net/docs/vt100-ug/chapter3.html) `ESC [ 6 n`.
  
  Cons: Need to update the table once the terminal settings get updated. Only VT100 terminals?

**Comment by jakwings** [comment]
Not even UTF-8?
