### ISSUE TITLE
[RFC] Environment Variables: Global & Local & Export & Import

### ISSUE THREAD

**Issue by ghost** [universal-shell/wip#7]
By default, functions need local scopes. We can provide a way to create local scopes too.

Also, sometimes environment variables need to be exported to sub-process.

What shall we do when:
- referring to a variable-in-outer-scope-with-export-bit?
- defining a variable of the same name of a variable-in-outer-scope but with a different export-bit?
- defining a global variable in the inner scope?

How to query the attributes of a variable?
And how to copy the attributes from one variable to another?

**Comment by jakwings** [comment]
Proposal 1: There is only one global scope.

Consequence:

* It is impossible or inadvisable to define a file-scope variable in an inner scope.

**Comment by ghost** [comment]
Proposal 1: A local variable does not inherit attributes from a variable of the same name in the outer scope by default.

Consequence:
- We need a simple way to query and borrow attributes from one variable to another.
- We may search for an exported variable of the same name in the outer scopes if it is not define with an export-bit in the local scope.

**Comment by ghost** [comment]
Proposal 2: Have a separate dictionary variable `$env` may be good to decouple `export` from the attributes of variables? When to copy the whole `$env` to a new local one?

Details:
- `$env` is not removable, but its key-value elements are removable.
- `$env` always exists, and its values are inherited from the outer scopes.

**Comment by jakwings** [comment]
Proposal 3: Setting the value of a global variable means that all variables of the same name from the current scope to the outermost scope are set to the same value.

**Comment by ghost** [comment]
Proposal 3: There is only one global scope, the outermost scope.
- Need a way to get/set the values of global variables.

**Comment by ghost** [comment]
Proposal 4: We can `import` into the local scope functions and variables from a file or stdin.
- The imported variables and functions cannot be brought to the outer scopes.

**Comment by ghost** [comment]
Proposal 5: Variables are local by default.
